/*
 * ULTRASONIC.h
 *
 *  Created on: Oct 13, 2023
 *      Author: karim
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define ULTRASONIC_TRIGGER_PORT PORTB_ID
#define ULTRASONIC_TRIGGER_PIN  PIN5_ID

//as we in atmega32 there is only one input capture unit through PD6/ICP1
#define ULTRASONIC_ECHO_PORT PORTD_ID
#define ULTRASONIC_ECHO_PIN  PIN6_ID

#define ULTRASONIC_TRIGGER_PULSE_DURATION 10

#include"std_types.h"


/***********************Function Prototypes*******************/

/*Description:
➢initialize the icu driver
➢setup the icu Call back func.
➢setup the direction of trigger pin as output*/
void Ultrasonic_init(void);

/*Description
➢ Send the Trigger pulse to the ultrasonic*/
void Ultrasonic_Trigger(void);
/*Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.*/
uint16 Ultrasonic_readDistance(void);
/*• Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.*/
void Ultrasonic_edgeProcessing(void);




#endif /* ULTRASONIC_H_ */
